# Generated by Django 2.0.5 on 2018-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=255)),
                ('when', models.CharField(max_length=255)),
                ('what', models.CharField(max_length=255)),
            ],
        ),
    ]
