# Generated by Django 2.0.5 on 2018-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='when',
            field=models.DateTimeField(),
        ),
    ]
